<a href="https://colab.research.google.com/github/akshattjain/MACHINE_LEARNING/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy  as np

In [ ]:
np_array =np.array([1,2,3,4,5])
print(np_array)
type(np_array )

[1 2 3 4 5]


numpy.ndarray

In [ ]:
z=np.full((4,5),6)
print (z)

[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]


In [ ]:
a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


random values


In [ ]:
c=np.random.randint(10,5000,(3,6))
print (c)

[[4952 3376 3051 3556 1232 2839]
 [ 889 3890 4808 4154 4991   36]
 [4443 1485  868 1635 4240 3237]]


In [ ]:
ab=c.reshape(6,3)
print (ab)

[[4952 3376 3051]
 [3556 1232 2839]
 [ 889 3890 4808]
 [4154 4991   36]
 [4443 1485  868]
 [1635 4240 3237]]
